### ISSUE TITLE
Front-end Preview page does not load enqued CSS and JS

### ISSUE THREAD

**Issue by Jamezsss** [studiopress/genesis-custom-blocks#125]
## Feature description
When creating a new block or editing an existing one, the Front-end Preview page does not load enqueued CSS and JS in functions.php using the enqueue_block_assets hook.

## Image
![image](https://user-images.githubusercontent.com/19152517/173919146-45d83926-1cbc-41d6-893a-6e7786263ab0.png)

## Use case
Show the block specific js/css in the Front-end Preview when creating or editing blocks. Now it looks completely weird and I couldn't find a hook for your Front-end Preview template.

## Additional information
(This could also be a bug but since I don't know if there is a hook for it I put it under Feature requests,

**Comment by sir-dunxalot** [comment]
This code seems to load JS and CSS in the editor:

```php
<?php
  function load_scripts() {
    $scriptUri = get_stylesheet_directory_uri() . '/blocks/my-block/script.js';

    wp_enqueue_script('get-script', $scriptUri);
  }

  add_action('enqueue_block_assets', 'load_scripts');
?>
```

However, I am unable to get `enqueue_block_assets` to fire on the frontend via Genesis Custom Blocks.

**Comment by kienstra** [comment]
Hi @Jamezsss,
Thanks for opening this, and sorry for the long delay.

This is probably a bug. But to be honest, we're not focusing on this plugin now, other than big bug fixes.
