### ISSUE TITLE
Inner Blocks not rendering SVG

### ISSUE THREAD

**Issue by robinschreiner** [studiopress/genesis-custom-blocks#129]
## Bug summary

When adding Inner Blocks, Inline SVGs in the Children are not rendered in the frontend.

## Steps to reproduce

Parent: 
_Parent Block_
```
<div>
    <ul role="list">
        <?php block_field('features'); ?>
    </ul>
</div>

```
_Features children Block_
```
<li class="feature-child">
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5"></path>
    </svg>
    <p><?php block_field('text'); ?></p>
</li>
```

_Rendered HTML_
```
<li class="feature-child"><p>test 3</p></li>
```

## Expected behavior
To have all markup in Inner Blocks get rendered OR information WHICH blocks are ignored or striped.

## Versions

 - WordPress version: 6.0.2
 - Genesis Custom Blocks version: 1.5.2
 - Gutenberg plugin version (if active): none
 - Other block-related plugins (if active): none
 - OS: Mac
 - Browser: Chrome
 - Device: MacBook (Latest Intel)

**Comment by robinschreiner** [comment]
This can be closed. Problem is not with genesis-custom-blocks. 

**For those struggling with the same Problem:**

While digging deeper, I discovered that WordPress itself is stripping the SVG based on restricted tags.
I had to add them to the allowed HTML in the `functions.php`

This is what helped for my SVG-File
```
add_filter('wp_kses_allowed_html', function ($tags) {
	$tags['svg'] = array(
		'xmlns' => array(),
		'class' => array(),
		'fill' => array(),
		'aria-hidden=' => array(),
		'stroke' => array(),
		'stroke-width' => array(),
		'viewbox' => array(),
		'role' => array(),
		'aria-hidden' => array(),
		'focusable' => array(),
	);
	$tags['path'] = array(
		'd' => array(),
		'fill' => array(),
	);
	return $tags;
}, 10, 2);
```

**Comment by kienstra** [comment]
@robinschreiner,
Thanks for letting me know about this, and for figuring out the cause.
