### ISSUE TITLE
Hide preview in editor completely and only show editor fields instead 

### ISSUE THREAD

**Issue by fabiankaimer** [studiopress/genesis-custom-blocks#132]
The Gutenberg editor is displaying a preview of my custom block based upon the `block.css` within the folder. Unfortunately the preview is a mess and I don't have the time and motivation to create a dedicated `preview.css` file for the editor. Is there any way to just display the editor fields within the gray box (the "default preview"?) instead of the actual block content preview? I really like the look and feel of the gray boxes. I have tried passing an empty `preview.css` and also an `preview.php` but it always seems to default to the preview from my `block.css`. Would be cool if somebody had an idea on that.

Edit: Actually, the empty preview.css and preview.php cause the editor to display nothing at all but that's also not a good solution :D

**Comment by kienstra** [comment]
Hi @fabiankaimer,
Sorry for the long delay. 

>Is there any way to just display the editor fields within the gray box (the "default preview"?) instead of the actual block content preview?

No, sorry. And we aren't planning on adding that feature, though it's a good idea.
