### ISSUE TITLE
Optimize Production Composer Build to reduce needless file lookups

### ISSUE THREAD

**Issue by andyblackwell** [studiopress/genesis-custom-blocks#133]
## Bug summary

I recently did an optimization pass on our sites, and after profiling them found that several plugins with local composer /vendor builds were not fully optimized for production, Genesis Custom Blocks (and Pro version) being in this list.

The plugin's local composer build is not built with `--classmap-authoritative`, and by default the composer ClassLoader will prepend itself to the list of autoloaders. Both of these issues combined can cause thousands of needless file lookups for classes flowing through this loader that it doesn't need to handle. When not built with `--classmap-authoritative` and a class isn't found in the local classmap, then composer makes a few fallback attempts to find the class, resulting in all the needless file lookups.

Looks like this plugin already uses `-o` when building, so would propose adding `-oa`
so adding either of these to the production build:  `-oa` or `--optimize-autoloader --classmap-authoritative`

and potentially also adding `prepend-autoloader: false` to the composer.json config, so this autoloader doesn't prepend itself ahead of other more site specific autoloaders:
```
"config": {
    "prepend-autoloader": false
}
```

## Steps to reproduce

would need to profile a site that has other autoloaders registered with this plugin included, to see the difference in file lookups

## Expected behavior
Expected behavior is that the local composer build **only** handles autloading the classes it includes.

## Actual behavior
Any unrelated class lookups flowing through the local autoloaders cause needless file lookups due to the composer fallback attempts at finding the class.

## Versions

 - WordPress version: 6.0.2
 - Genesis Custom Blocks version: 1.5.1 (pro)
 - Gutenberg plugin version (if active):
 - Other block-related plugins (if active):
 - OS:
 - Browser:
 - Device:

**Comment by kienstra** [comment]
Hi @andyblackwell,
Sorry for the delay.

This is a good idea, but I don't know much about Composer. 

There's risk of regression, and I'm not sure how much time we'll actually save in loading files.

**Comment by andyblackwell** [comment]
k, I don't have a dog in the fight anymore (different job), but it was a significant time/cost savings, and the '-oa' change would be pretty safe for you and is a more proper setup, we ran with both changes in production with no issues.

**Comment by kienstra** [comment]
Hi @andyblackwell,
Thanks for letting me know. I'll test this.

Sorry for the very long delay getting back to you, and thanks for the care you took opening this PR and adding your details.
