### ISSUE TITLE
Icon codes should be documented

### ISSUE THREAD

**Issue by mikemanger** [studiopress/genesis-custom-blocks#142]
## Feature description
It would be great if the icon codes were better documented. To work them out we either have to hunt through the source code or use the editor to export a block. This makes programmatically creating blocks with `add_block()` or `blocks.json` a little bit tiring.

Similarly the syntax for setting the `category` is not super clear (is it a string for `add_block()` and an object for `blocks.json` which seems to support icons).

**Comment by fatimaMarzouq** [comment]
great notice it would be nice if they document the other fields in more detail also

**Comment by kienstra** [comment]
Hi @mikemanger,
Thanks, you're right that icon codes should be documented. But to be honest, we're not going to, as we're not focusing on Genesis Custom Blocks.

Here's how to get the 'icon' for `add_block()`:

1. Find an icon [here](https://github.com/studiopress/genesis-custom-blocks/tree/develop/js/src/common/icons) (I know there's no way to see the icon there, it's a bad experience)
2. Convert the JS file path name to camel case. For example, convert `account-balance.js` to `account_balance`.
3. Pass that to `add_block()` as the `'icon'`:

```php
add_block(
	'your-example-block
		[
			'title'    => __( 'Your Example Blok', 'your-textdomain' ),
			'category' => 'common',
			'icon'     => 'account_balance',
			...
```
