### ISSUE TITLE
Fetching Error in Preview if InnerBlock has too much content

### ISSUE THREAD

**Issue by rocketluz** [studiopress/genesis-custom-blocks#144]
## Bug summary

If a page hast one or more genesis-custom-blocks (gcb) and one of them has an innerBlock with too much content, all gcb will be shown as offline (preview not shown). The reason for it is, that the content of the innerBlock is added as query parameter (inner_blocks) to the query URL. In some cases, this query parameter gets too long.

## Steps to reproduce

1. Create a gcb with the field type innerBlock
2. As preview you can add any Text or just add {{ $inner_block }}
3. Add this gcb to the page and add a lot of content to it
4. Now the preview is not showing up. Instead a php-warning is shown
5. If you add some other gcb, then save and reload the page -> all previews of gcb failed
6. when you edit a gcp (not the gcb from section 1), the preview is now shown for this gcb

## Expected behavior
1. the preview for all gcb is showing up correctly
2. for gcb with an innerBlock in the preview is shown the content or give a hint that it is only visible in edit-mode (if too much content)

## Actual behavior
<img width="374" alt="image" src="https://github.com/studiopress/genesis-custom-blocks/assets/59647231/1cd35fe2-d009-4371-8668-0f8f3769529a">

## JS Console
<img width="1069" alt="image" src="https://github.com/studiopress/genesis-custom-blocks/assets/59647231/8a50d1fa-87cc-4f05-87b0-8f6e40e1f100">

## Additional information
- Problem occurs with the introduction of the new Feature "Allow previewing InnerBlocks in the block editor" (plugin v1.4.1)
https://github.com/studiopress/genesis-custom-blocks/pull/114
- My suggestion is to limit the length of the query parameter inner_block and if it is reached, add a hint that the content is not visible in the preview

## Suspected cause (optional)
- some server has restrictions of url length or query length

## Versions
 - WordPress version: 6.2.2
 - Genesis Custom Blocks version: v1.5.1
 - Browser: Google Chrome
 
<img width="766" alt="image" src="https://github.com/studiopress/genesis-custom-blocks/assets/59647231/95787333-4e7f-470c-8558-39b44c0aebaf">

**Comment by rocketluz** [comment]
Here is an actual workaround I made to handle it.

[genesis-custom-blocks-pro_innerblock-workaround.zip](https://github.com/studiopress/genesis-custom-blocks/files/11895305/genesis-custom-blocks-pro_innerblock-workaround.zip)

**Comment by kienstra** [comment]
Hi @rocketluz,
Thanks for opening this, and you're right that it's a bug, and one that a lot of people have found.

But I don't see a clean fix to it.

**Comment by rocketluz** [comment]
Hi @kienstra

I understand, I haven't found a clever solution myself that works in every case. However, I have a suggestion for a solution. With the help of a checkbox in the settings of the inner block, you could define whether the content should be displayed in the preview or whether a note should be displayed. It would be even better if, instead of the checkbox, you could define a maximum content length that is displayed in the preview.
