### ISSUE TITLE
Custom Blocks blocks.css shoud not override WordPress Theme Customizer Additional CSS

### ISSUE THREAD

**Issue by foliovision** [studiopress/genesis-custom-blocks#154]
## Bug summary

The blocks.css file loads in the footer. So if you use a set of custom blocks and then want to use the core WordPress Additional CSS field in theme customizer your rules are not going to work and you will have a hard time getting them to work.

## Steps to reproduce

1. Create your custom block.
2. Use your block in the page.
3. Add in blocks/blocks.css to your theme folder, see https://developer.wpengine.com/genesis-custom-blocks/?s=blocks.css#global-stylesheet

## Expected behavior

Your custom blocks.css should load in header, before the customizer CSS code.

## Actual behavior

The blocks.css file loads in footer, after all the other CSS code. That way it overrides your custom CSS from customizer.

## JS Console

None.

## Versions

 - WordPress version: 6.2.2
 - Genesis Custom Blocks version: 1.5.1 (Pro)
 - Gutenberg plugin version (if active):
 - Other block-related plugins (if active):

**Comment by kienstra** [comment]
Hi @foliovision,
You're right about this. It probably should have been that way from the beginning.

But I'm worried this will cause regressions on sites where people are depending on the current loading order.

**Comment by foliovision** [comment]
Hello @kienstra,

I see what you mean. In that case I would still suggest you to improve this and then add a new option named like "Legacy blocks.css loading" and have that enabled for existing users of the plugin, but the new users would get the proper loading order.

Thanks,
Martin
