### ISSUE TITLE
The custom content block (with a field like "Inner Block") does not display custom blocks

### ISSUE THREAD

**Issue by Andreslav** [studiopress/genesis-custom-blocks#161]
## Bug summary

The custom content block (with a field like "Inner Block") does not display custom blocks.

## Steps to reproduce

1. Create a custom block (N1) with the "Inner Block" field.
![изображение](https://github.com/studiopress/genesis-custom-blocks/assets/39444579/1d38e251-7ec2-400a-897e-860e6f47e88b)

2. Create a second custom block (N2) with a text field.
![изображение](https://github.com/studiopress/genesis-custom-blocks/assets/39444579/026a4138-e91b-4ee2-9300-ef299a299faa)

3. In the editor, place block N2 into N1. Also add two paragraphs with 1 and 2.
![2023-10-07_234310](https://github.com/studiopress/genesis-custom-blocks/assets/39444579/5e752f24-f50d-42d0-9937-4ae66037a930)

5. Exit editing the block.
![2023-10-07_234328](https://github.com/studiopress/genesis-custom-blocks/assets/39444579/0f2f0cee-b147-4153-b78e-f7c7aa1e2988)

## Expected behavior
Between 1 and 3, you should see 2, which is entered in the field in block N1.

## Actual behavior
2 is not displayed between 1 and 3.

## JS Console
There is nothing unusual in the console: no errors or warnings.

## Additional information
On the website, after the page is published, the content is rendered correctly.
![изображение](https://github.com/studiopress/genesis-custom-blocks/assets/39444579/f5c3b4ae-7c47-4647-9737-9c4b07d3fd31)

## Versions

 - WordPress version: 6.3.1
 - Genesis Custom Blocks version: 1.5.2
 - Gutenberg plugin version (if active): -
 - Other block-related plugins (if active):
 - OS: Windows 10
 - Browser: Firefox 118.0.1

**Comment by kienstra** [comment]
Hi @Andreslav,
Sorry, I'm not going to fix this, as I don't see a clean way. 

Similar to https://github.com/studiopress/genesis-custom-blocks/issues/162.

**Comment by Andreslav** [comment]
Hi @kienstra,
One more thing: Block styles (block.css) are not applied in the Site Editor (/wp-admin/site-editor.php) when using a Block Theme.

1. Activate the Twenty Twenty-Three theme.
2. Go to Appearance > Editor > Pages > Home (or other) > Edit > Add a custom block to the page if not previously added.

**Comment by kienstra** [comment]
Hi Andre,
Thanks for letting me know. Unfortunately, we're only fixing security issues and critical bugs.
