### ISSUE TITLE
414 Request-URI Too Large nginx/1.16.0

### ISSUE THREAD

**Issue by Andreslav** [studiopress/genesis-custom-blocks#162]
## Bug summary

If you put enough content in the "Inner Block", the editor will display the error "Error loading block: Response is not a valid JSON response".

## Steps to reproduce

1. Create a custom block (N1) with the "Inner Block" field.
![273408509-1d38e251-7ec2-400a-897e-860e6f47e88b](https://github.com/studiopress/genesis-custom-blocks/assets/39444579/1515a559-c4ef-464a-9b27-db79fce1b594)

2. Put a large arbitrary text in it (I generated it):

> Повседневная практика показывает, что постоянный количественный рост и сфера нашей активности представляет собой интересный эксперимент проверки форм развития. Задача организации, в особенности же новая модель организационной деятельности позволяет выполнять важные задания по разработке новых предложений. Товарищи! дальнейшее развитие различных форм деятельности в значительной степени обуславливает создание существенных финансовых и административных условий. Значимость этих проблем настолько очевидна, что консультация с широким активом в значительной степени обуславливает создание модели развития. Задача организации, в особенности же дальнейшее развитие различных форм деятельности в значительной степени обуславливает создание новых предложений. Разнообразный и богатый опыт сложившаяся структура организации требуют определения и уточнения модели развития.

3. Exit editing the block.

## Expected behavior
The entered text should be displayed.

## Actual behavior
Instead of the entered text, the error "Error loading block: Response is not a valid JSON response" is displayed.

## JS Console
Failed request for an address like `/wp-json/wp/v2/block-renderer/genesis-custom-blocks/N1?context=edit&post_id=2&inner_blocks=%3C!--%20wp%3Agroup%20%7B%……`. 414 Request-URI Too Large

## Additional information
On the website, after the page is published, the content is rendered correctly.

## Suspected cause (optional)
Too much data is passed in the url parameter, should be passed via post.

## Versions
 - WordPress version: 6.3.2
 - Genesis Custom Blocks version: 1.5.2
 - Gutenberg plugin version (if active): -
 - Other block-related plugins (if active): -
 - OS: Windows 10
 - Browser: Firefox 118.0.1

**Comment by kienstra** [comment]
Hi @Andreslav,
Thanks for opening this. But I don't see a clean fix for it, so I'm not going to fix it.

As you mentioned, the inner blocks go to the server via a request parameter, which is a hack (that I wrote 😄).

But I couldn't find another way, as `<ServerSideRender>` doesn't render inner blocks.
