### ISSUE TITLE
Produce simple XML config file on save for easy translation of blocks with WPML

### ISSUE THREAD

**Issue by richardpbull** [studiopress/genesis-custom-blocks#38]
## Feature description
genesis-custom-blocks are not translatable (or at least are not recognised) by WPML's Advanced Translation Editor (ATE) which is an excellent, well developed tool for managing website translations. 

Producing an XML config file so that the ATE can recognise the content of the GCB made block seems to be straighforward, just needs a bit of cut pasting, and it works. 

For a site with many custom blocks, this would be onerous to manage. It should be very easy to automate the XML config file generation, even if it needs cut pasting over to WPML.

I think a good first phase result would be to talk with WPML and automate the generation of the XML for the Genesis Custom Blocks plugin, which could then easily be cut paste into the correct place.
From [https://wordpress.org/support/topic/translation-of-blocks-with-wpml/](https://wordpress.org/support/topic/translation-of-blocks-with-wpml/)

## Image

```
<wpml-config>
    <gutenberg-blocks>
        <gutenberg-block type="genesis-custom-blocks/race-subtitle" translate="1">
            <key name="race-sub-title"></key>
        </gutenberg-block>
    </gutenberg-blocks>
</wpml-config>
```

## Use case
After designing a block & uploading a php template, I would like to immediately be able to create a block on a page (in English, or the default language) using the Gutenberg editor, and then translate the block, using WPML's Advance Translation Editor (ATE).

## Additional information
Thanks!

**Comment by kienstra** [comment]
Hi @richardpbull,
Thanks a lot for opening this, and for your great details.

For the keys, like:

```
<key name="race-sub-title"></key>
```

...should all of them be translatable? 

Some fields might lend themselves to translation more than others:
```
Text
Textarea			
URL	
Email		
Number				
Color				
Image				
Select				
Multi-Select			
Toggle				
Range				
Checkbox			
Radio				
```

**Comment by richardpbull** [comment]
That's right. Obviously text needs translation, a radio button / email / color etc probably not. The only things that might change are URL, which might need to point to a translated page (and might not) and media, which might need to point to a translated image (imagine a diagram with text on it, or a image of a poster with text, which could have a copy of the English original with translated text, alt text, caption etc.)
So to be honest that would be something to ask WPML about. Sounds like a shrug from me, but really they are super enthusiastic to help, especially with "game changer" plugins like this. Have a read here to start...
https://wpml.org/purchase/theme-and-plugin-developers/
Many thanks for being open to this!

**Comment by kienstra** [comment]
Ah, thanks for that link for getting a free subscription.

Would a WP-CLI script help for this? Maybe `wp eval-file bin/wpml-compat.php` Maybe that could create the WPML config file.

It wouldn't be bundled with the plugin on wp.org, but it might be in this GitHub repo's `bin/` directory.

**Comment by richardpbull** [comment]
ACF has it's own plugin called ACF Multilingual and it's collaborative between ACF & WPML, but I think WPML takes ownership of it. It works invisibly with no UI.
https://wpml.org/version/acfml-0-9/
I can't suggest what method would be most useful, I assume a great deal of your user base will be English or one language only. 
WPML has worked with a huge number of plugin developers, so give them a shout and see what they come back with. 
Sorry I can't help more. I am a user rather than a developer!

**Comment by kienstra** [comment]
Ah, thanks a lot for that link. I'll look at that.

**Comment by richardpbull** [comment]
Is there a mailing list I can join to learn about updates, for instance if this was implemented?

**Comment by kienstra** [comment]
We'll link to a PR here if there is one.

**Comment by kienstra** [comment]
Unfortunately, if this does mean a separate standalone plugin, like ACF has, I don't think we're going to have time for this soon. We're already maintaining this plugin, the Pro plugin, and Block Lab.

**Comment by kienstra** [comment]
Closing this, as we're not planning on this. I'll reopen it if we ever do.
