### ISSUE TITLE
wrong path to css files in roots bedrock env. (fix included)

### ISSUE THREAD

**Issue by lemon3** [studiopress/genesis-custom-blocks#66]
## Feature description
please update the function get_url_from_path() in class-util.php

## Use case
roots bedrock environment

## Additional information
the "updated" get_url_from_path() function in class-util.php
```
public function get_url_from_path( $path ) {
	$is_bedrock = basename(WP_CONTENT_DIR) === 'app';
	if ($is_bedrock) {
		$uri = get_stylesheet_directory_uri();
		$theme_name = basename($uri);
		$rel_path = substr($path, strrpos($path, $theme_name) + strlen($theme_name));
		return $uri . $rel_path;
	}

	$abspath = ABSPATH;
	// Workaround for weird hosting situations.
	if ( trailingslashit( ABSPATH ) . 'wp-content' !== WP_CONTENT_DIR && isset( $_SERVER['DOCUMENT_ROOT'] ) ) {
		$abspath = sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) );
	}

	$stylesheet_url = str_replace( untrailingslashit( $abspath ), '', $path );

	return $stylesheet_url;
}
```

**Comment by kienstra** [comment]
Hi @lemon3,
Sorry for the long delay in replying. 

Would a filter at the bottom of `get_url_from_path()` help?

Maybe like:

```php
return apply_filters( 'genesis_custom_blocks_get_url_from_path', $stylesheet_url, $path );
```

Otherwise, I'm not sure about referencing another setup like bedrock from within this plugin.

Sorry for the delay.

**Comment by IsabelBothe** [comment]
👍  could you please make it possible, so that the preview / styles could be used in bedrock???

**Comment by kienstra** [comment]
Hi @IsabelBothe,
Sorry for the long delay replying to you.

> 👍 could you please make it possible, so that the preview / styles could be used in bedrock???

Sorry, we're probably not going to do this, though that unfortunately means leaving out Bedrock users.
