### ISSUE TITLE
Change `master` branch name

### ISSUE THREAD

**Issue by lukecarbis** [studiopress/genesis-custom-blocks#7]
Following the example of WordPress core, Redis, Chromium, and other open source projects, Genesis Custom Blocks should remove references to `master` and replace them with something else, as a part of clearing references to systems of oppression that exist in the world.

Master as the primary branch in git has its roots in [BitKeeper](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html) which explicitly used it to mean master/slave relationships.

This may require updates to scripts so everything continues to function correctly.

Alternate branch names for consideration:
- `main`
- `trunk`

WordPress core is moving to [`trunk`](https://make.wordpress.org/core/2020/06/18/proposal-update-all-git-repositories-to-use-main-instead-of-master/), due in part to its roots in SVN. GitHub is switching to [`main`](https://twitter.com/natfriedman/status/1271253144442253312) as the new default branch. Gitlab is also switching to [`main`](https://gitlab.com/gitlab-org/gitlab/-/issues/221164).

My preference is to use `main`.

Another option is to use `develop` as our primary branch, and not have a "stable" master. We can use releases for that.

**Comment by kienstra** [comment]
The `master` branch is now deleted. There's already a `main` branch, which we could use as the new stable branch.

I think it'd be good to keep a stable branch. It could make it easier to onboard if we have more contributors.

**Comment by kienstra** [comment]
Closing this if that's alright, feel free to reopen or comment.
