### ISSUE TITLE
The response is not a valid json response error

### ISSUE THREAD

**Issue by ghost** [studiopress/genesis-custom-blocks#88]
## Bug summary

Starting with the version 1.3 all the blocks preview that have fields (text or textarea) **with HTML tags** (`<span>` usually) returns in Chrome console 403 errors. (This happens only on DEV or LIVE instances, not on localhost).

## Steps to reproduce

1. Edit a page in backend.

## Expected behavior
To show the preview of the block.

## Actual behavior
Not loading the block preview.

## JS Console
See the screenshot.
![screenshot](https://user-images.githubusercontent.com/16556688/128146925-442a829b-5491-4ccf-91f6-e8af97e3f461.jpg)

## Additional information

The block can be edited without a problem  and works fine in frontend, but in backend is confusing when returns this message "The response is not a valid json response error". (When I click on it can be edited without a problem, but it isn't ok to show an error in preview mode).

## Suspected cause (optional)
HTML tags written in text or textarea fields. Should be able to add HTML tags (span, div, ul, ol...) with id or class and the preview should be working.

## Versions

 - WordPress version: 5.8
 - Genesis Custom Blocks version: 
 - Gutenberg plugin version (if active): Yes
 - Other block-related plugins (if active): No
 - OS: Win 10
 - Browser: Chrome
 - Device: PC

**Comment by kienstra** [comment]
@standoski,
Thanks for your great details!

**Comment by kienstra** [comment]
Just heard this from another user!

**Comment by ChristineShiels** [comment]
Yes! I am literally having the exact same issue, except I'm using Firefox, and I've tried every html tag I can think of, but am only having this issue with <script></script> and noscript /noscript, all other tags I've tested don't produce the error. edit: looks like there's no love for noscript here either 😂

**Comment by kienstra** [comment]
@ChristineShiels,
Thanks for letting me know about that. I'll look at this more, it's one of the more important bugs.

**Comment by kienstra** [comment]
Hi @standoski,
Sorry for the long delay.

If this is still of interest, `echo block_value()` might help.

`block_field()` is [escaped](https://github.com/studiopress/genesis-custom-blocks/blob/d7b58815da17fd868c86f397db3cd55582b8e04b/php/Helpers.php#L81-L86), which might have caused this error.
