### ISSUE TITLE
Broken display of non-ascii translated characters in post editor

### ISSUE THREAD

**Issue by knutsp** [studiopress/genesis-custom-blocks#90]
## Bug summary

When æ, ø, å are part of the example block translated field descriptions, they are shown as numeric codes

Example: "æ" shows as 00e6 and "å" shows as 00e5

![bilde](https://user-images.githubusercontent.com/1531128/128999697-a838936e-488e-4a74-aeb9-8269509deeec.png)

 - Browser: Firefox

**Comment by kienstra** [comment]
@knutsp,
Thanks for opening this, and for your nice screenshot.

**Comment by kienstra** [comment]
To be honest, we're not planning on fixing this, though it's a valid bug.
