### ISSUE TITLE
Add support for block's alignment in custom blocks

### ISSUE THREAD

**Issue by aryanrajseo** [studiopress/genesis-custom-blocks#91]
## Bug summary

Blocks created with Genesis Custom Blocks not supports align the custom block making it difficult to align the block container.

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#align

## Steps to reproduce

Create a Custom Block and add it in any Post Page to try to locate the option to make it wide. 
![9BA39B31-B5A1-460C-BE27-CDCEB1D605BD](https://user-images.githubusercontent.com/34836534/129382848-1dd2db6a-fa94-4945-a115-e2fe63fcfc14.png)

## Actual behavior
The General support for align like Image should be added or a way to support it natively or using the code builder.
![FDB971B1-01D1-4DBD-AA2A-BBE25CB55755](https://user-images.githubusercontent.com/34836534/129383284-18e76343-f15f-4a9b-bb11-70882cf44c8f.png)

## Versions

 - WordPress version:
 - Genesis Custom Blocks version: 
 - Gutenberg plugin version (if active):
 - Other block-related plugins (if active):
 - OS:
 - Browser:
 - Device:

**Comment by kienstra** [comment]
Hi @aryanrajseo,
Thanks, this is a good idea. But we're not adding features to this plugin.
