### ISSUE TITLE
Block categories duplicates

### ISSUE THREAD

**Issue by smesterheide** [studiopress/genesis-custom-blocks#92]
## Bug summary

When assigning a block to a category, the category is duplicated. This also happens with default categories. It shows twice in the plugin's block list and the inserter.

## Versions

 - WordPress version: 5.8
 - Genesis Custom Blocks version: 1.3

**Comment by kienstra** [comment]
@sambrezo, interesting, thanks for letting me know!

**Comment by ttstauss** [comment]
I'm getting the same issue. Goes away when I disable the plugin. In my case, it's showing the category three times...

![Screenshot 2022-03-12 131153](https://user-images.githubusercontent.com/15224340/158033508-fc06c8ea-0154-429e-9c2f-80152e3e0b35.png)

**Comment by kienstra** [comment]
@ttstauss, thanks for letting me know about that, and for your great screenshot.

**Comment by kienstra** [comment]
This should be fixed now.
