### ISSUE TITLE
Remove Modal Popup Notice When clicking on block.

### ISSUE THREAD

**Issue by webplantmedia** [studiopress/genesis-custom-blocks#97]
## Feature description
Please see screenshot below. It is not user friendly to get this popup every time I select my block when all my fields are inspector fields. Can you please remove that popup notice. It's one extra click which slows down editing. 

## Image
https://www.screencast.com/t/HEbw6nEVi

**Comment by kienstra** [comment]
Hi @webplantmedia,
Sorry for the long delay.

If you're still interested, have you thought about unchecking "Open block fields in a modal"?

<img width="822" alt="Screenshot 2023-08-10 at 1 38 31 PM" src="https://github.com/studiopress/genesis-custom-blocks/assets/4063887/f751ad16-fdc6-42e7-ba32-00307b547597">

Though you probably checked that for a reason.
